### ISSUE TITLE
Multiple tkinter instances

### ISSUE THREAD

**Issue by WK-GiHu** [JDJacinto29/StackOverflow#2]
@JDJacinto29 

Here you create the **First** `tkinter` instance by calling a `tkinter` object 
https://github.com/JDJacinto29/StackOverflow/blob/939d84db59f7b3d20112c4bdce841f5bd06c21da/SetIPexample.py#L57

Here you create explecit the **Second** `tkinter` instance
https://github.com/JDJacinto29/StackOverflow/blob/939d84db59f7b3d20112c4bdce841f5bd06c21da/SetIPexample.py#L271

Here you bind to `root`, **Second** `tkinter` instance:
https://github.com/JDJacinto29/StackOverflow/blob/939d84db59f7b3d20112c4bdce841f5bd06c21da/SetIPexample.py#L101

Here you **don't** bind to a parent which leads to undefind behavior and probably defaults to the **First** `tkinter` instance:
https://github.com/JDJacinto29/StackOverflow/blob/939d84db59f7b3d20112c4bdce841f5bd06c21da/SetIPexample.py#L112
https://github.com/JDJacinto29/StackOverflow/blob/939d84db59f7b3d20112c4bdce841f5bd06c21da/SetIPexample.py#L120

**Comment by JDJacinto29** [comment]
@WK-GiHu I pushed an update. Thanks for the explanations, really helping me understand how this works. I explicitly called the other two string variables on root, and commented out the first filedialog call to debug for now since it's not critical. I'm still having it crash on the same error, any suggestions?
