### ISSUE TITLE
4 times `root.destroy()`

### ISSUE THREAD

**Issue by WK-GiHu** [JDJacinto29/StackOverflow#3]
>I'm still having it crash on the same error, any suggestions?

_Originally posted by @JDJacinto29 in https://github.com/JDJacinto29/StackOverflow/issues/2#issuecomment-573797863_

**Comment by WK-GiHu** [comment]
@JDJacinto29 

You are calling 4-times `root.destroy()`
1. https://github.com/JDJacinto29/StackOverflow/blob/ae1de23621a227bb9b2ddfaeb2fd6bd585943a1d/SetIPexample.py#L156
2. https://github.com/JDJacinto29/StackOverflow/blob/ae1de23621a227bb9b2ddfaeb2fd6bd585943a1d/SetIPexample.py#L161
3. https://github.com/JDJacinto29/StackOverflow/blob/ae1de23621a227bb9b2ddfaeb2fd6bd585943a1d/SetIPexample.py#L166
4. https://github.com/JDJacinto29/StackOverflow/blob/ae1de23621a227bb9b2ddfaeb2fd6bd585943a1d/SetIPexample.py#L171

### You didn't have to call `root.destroy()` explicit.
The `root` instance of `tkinter` get destroyed by default on exit the Python script.

**Comment by JDJacinto29** [comment]
@WK-GiHu these are in separate helper methods, only one will ever be called and the script will be ended. However, I went ahead and replaced them all with exit() instead as it's probably better practice, so that now root will be implicitly destroyed when any of those 4 buttons are clicked. Doesn't seem to be causing the variable issue. I pushed an update
