### ISSUE TITLE
_tkinter.TclError: can't set "PY_VAR0": can't set "PY_VAR2": 

### ISSUE THREAD

**Issue by WK-GiHu** [JDJacinto29/StackOverflow#4]
@JDJacinto29 

>_tkinter.TclError: can't set "PY_VAR0":

This is `PY_VAR0`:
https://github.com/JDJacinto29/StackOverflow/blob/3638ef29ecc8ba2ad18eda0d643688cdf5620429/SetIPexample.py#L101

Therefore the `_tkinter.TclError` is related to `tkvar`

---

>_tkinter.TclError: can't set "PY_VAR2": 

This is `PY_VAR2`
https://github.com/JDJacinto29/StackOverflow/blob/3638ef29ecc8ba2ad18eda0d643688cdf5620429/SetIPexample.py#L120

Therefore the `_tkinter.TclError` is related to `updateSM`

---

### At which point of your programm are **both** variable accessed?

Describe a reproducible `input` and `click` codeflow to get the titles `_tkinter.TclError`.

**Comment by JDJacinto29** [comment]
@WK-GiHu I am able to achieve the error consistently by  Opening the optionbox in the interface at the top of the GUI (labeled site ID), selecting the option "Add Custom", and entering a new Item (choose any unique name). Repeating this process eventually causes the crash, usually on the first or second entry, but it can take up to about 10 or 15 tries from what I can tell.

**Comment by WK-GiHu** [comment]
@JDJacinto29 

Change this Line 220
https://github.com/JDJacinto29/StackOverflow/blob/3638ef29ecc8ba2ad18eda0d643688cdf5620429/SetIPexample.py#L220

to
```
if 0 and tkvar.get() == "Add Custom...": 
```

and try to reproduce the `_tkinter.TclError`

**Comment by JDJacinto29** [comment]
@WK-GiHu Hmmm looks like changing that line causes it to skip the if statement altogether. It attempts to run the else statement which crashes because it's now searching for "Add Custom" in the ini file, which by design, is not included in there. 

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 3285, in __call__
    self.__var.set(self.__value)
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 260, in set
    return self._tk.globalsetvar(self._name, value)
_tkinter.TclError: can't set "PY_VAR0": 
Traceback (most recent call last):
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\configparser.py", line 1136, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'Add Custom...'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\tkinter\__init__.py", line 1549, in __call__
    return self.func(*args)
  File "C:\Users\jjacinto\Desktop\StackOverflow\SetIPexample.py", line 226, in changeSiteID
    updateIP.set(config.get(tkvar.get(),'targetip'))
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\configparser.py", line 779, in get
    d = self._unify_values(section, vars)
  File "C:\Users\jjacinto\AppData\Local\Programs\Python\Python35-32\lib\configparser.py", line 1139, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'Add Custom...'`

**Comment by WK-GiHu** [comment]
@JDJacinto29 

>skip the if statement altogethe

Yes, that was intentional.
We see the `_tkinter.TclError: can't set "PY_VAR0":` also:

---

OK, disable this Line 108
https://github.com/JDJacinto29/StackOverflow/blob/3638ef29ecc8ba2ad18eda0d643688cdf5620429/SetIPexample.py#L108

Insert after Line 212
https://github.com/JDJacinto29/StackOverflow/blob/3638ef29ecc8ba2ad18eda0d643688cdf5620429/SetIPexample.py#L212
```
changeSiteID(None, None, None):
```

and try to reproduce the _tkinter.TclError

**Comment by JDJacinto29** [comment]
@WK-GiHu Ah got it. Ok with those changes, the user prompt that usually comes up when hitting "Add Custom..." is now bypassed, so I can't test it in the same way I was previously. However, repeatedly hitting the "Add Custom..." button does not seem to generate any errors

**Comment by WK-GiHu** [comment]
@JDJacinto29 

>Ok with those changes, the user prompt that usually comes up when hitting "Add Custom..." is now bypassed,

Revert all changes, this is a dead end ....
Continue with https://github.com/JDJacinto29/StackOverflow/issues/5
